title: "PhD Progress Tracker"
description: "Track PhD progress with ease!"
theme: minima
baseurl: ""  # Leave empty for the root
url: "https://masterpranjal.github.io/pranjal.github.io/"  # Replace with your GitHub Pages URL
