title: "PhD Progress Tracker"
description: "Track PhD progress with ease!"
theme: minima
baseurl: "/pranjal.github.io"  # Adjust this if your repository name is different
url: "https://masterpranjal.github.io"  # Your GitHub URL
